version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ferntrail-bitgarth_web_1
      APP_PORT: 8080

  web:
    image: bitgarth/bitgarth:0.1.8@sha256:96fb7505b05ae93639dbd3c0b42646d6ba7fbc16484c1a9accf6e6df158ed480
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      BITGARTH_CHANNEL: umbrel
