version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ferntrail-bitgarth_web_1
      APP_PORT: 8080

  web:
    image: bitgarth/bitgarth:0.1.7@sha256:5b739528a1303657d6314bc05d76e2fd79d3d45bb98705f81f4bf1d587bcfc93
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      BITGARTH_CHANNEL: umbrel
