version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ferntrail-bitgarth_web_1
      APP_PORT: 8080

  web:
    image: bitgarth/bitgarth:0.1.6@sha256:c6a7170ee02d263a897c6da33545ae99320388a891481dcf3a22e484373a31a9
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      BITGARTH_CHANNEL: umbrel
